# docker-compose up --build
version: "3"
services:
  admin:
    build:
      context: ./admin
    ports:
      - "8081:8081"

  server:
    build:
      context: ./serve
    environment:
      - MONGODB_URL='mongodb+srv://user:password@cluster0.b9vurxx.mongodb.net/node-vue-moba?retryWrites=true&w=majority'
    ports:
      - "3001:3001"

  neteasecoudmusicapi:
    build:
      context: ./NeteaseCloudMusicApi
    ports:
      - "3000:3000"

  music:
    build:
      context: ./
    ports:
      - "8080:8080"
